[tool.poetry]
name = "duck-orm"
version = "0.1.0"
description = "ORM Async for Python"
authors = ["Rich <richelton14@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
databases = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
aiosqlite = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
